name: Debian stable:amd64 Makefile
on:
  push:
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    env:
      CC: x86_64-linux-gnu-gcc
      LDFLAGS: -Wl,-fuse-ld=gold
      OBJCOPY: x86_64-linux-gnu-objcopy
      OBJDUMP: x86_64-linux-gnu-objdump
      PKG_CONFIG_PATH: /usr/lib/x86_64-linux-gnu/pkgconfig

    steps:
      - uses: actions/checkout@v4
      - name: Build
        shell: bash
        run: |
          # apt_toolchain
          echo -e "\e[0Ksection_start:`date +%s`:apt_toolchain[collapsed=true]\r\e[0KInstalling toolchain packages"
          sudo apt-get update
          sudo apt-get install gcc-x86-64-linux-gnu || apt-get install gcc
          # apt_toolchain
          echo -e "\e[0Ksection_end:`date +%s`:apt_toolchain\r\e[0K"

          # apt_development
          echo -e "\e[0Ksection_start:`date +%s`:apt_development[collapsed=true]\r\e[0KInstalling development packages"
          sudo apt-get install libsdl2-mixer-dev:amd64 libpng-dev:amd64 libcurl4-openssl-dev:amd64 libgme-dev:amd64 libopenmpt-dev:amd64 libminiupnpc-dev:amd64
          # apt_development
          echo -e "\e[0Ksection_end:`date +%s`:apt_development\r\e[0K"

          # make
          echo -e "\e[0Ksection_start:`date +%s`:make[collapsed=false]\r\e[0KCompiling SRB2"
          make --directory=src --keep-going LINUX64=1 || make --directory=src --keep-going LINUX64=1
          # make
          echo -e "\e[0Ksection_end:`date +%s`:make\r\e[0K"
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-${{ github.sha }}-x86-64-makefile
          path: |
            bin/
            src/comptime.h
