name: Windows x64 Makefile
on:
  push:
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    env:
      PREFIX: x86_64-w64-mingw32

    steps:
      - uses: actions/checkout@v4
      - name: Build
        shell: bash
        run: |
            # apt_toolchain
            echo -e "\e[0Ksection_start:`date +%s`:apt_toolchain[collapsed=true]\r\e[0KInstalling toolchain packages"
            sudo apt-get install gcc-mingw-w64-x86-64-win32
            # apt_toolchain
            echo -e "\e[0Ksection_end:`date +%s`:apt_toolchain\r\e[0K"
            # make
            echo -e "\e[0Ksection_start:`date +%s`:make[collapsed=false]\r\e[0KCompiling SRB2"
            make --directory=src --keep-going MINGW64=1 SDL=1 || make --directory=src --keep-going MINGW64=1 SDL=1
            # make
            echo -e "\e[0Ksection_end:`date +%s`:make\r\e[0K"
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-${{ github.sha }}-Win64-makefile
          path: |
            bin/
            src/comptime.h
